finish lock
layotto/java-sdk pull request #18
Opened 2022-04-25 11:39 UTC by akkw

Distributed lock implementation

2022-04-25 11:42 UTC, seeflood commented
Thanks for your contribution!
@ZLBer   @kevinten10 Could u help review this PR ? I'm on call this week and might be slow to reply 😢

2022-04-25 12:51 UTC, ZLBer commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new RuntimeClientException(e);
add error logs

2022-04-25 12:51 UTC, ZLBer commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new RuntimeClientException(e);
add error logs

2022-04-25 13:44 UTC, akkw commented on examples/src/test/java/io/mosn/layotto/examples/lock/EtcdLock.java
> +import java.util.concurrent.CountDownLatch;
ok

2022-04-25 13:44 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new RuntimeClientException(e);
ok

2022-04-25 13:44 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new RuntimeClientException(e);
ok

2022-04-25 15:10 UTC, ZLBer submitted a review, later dismissed
LGTM,  thanks for your contribution

2022-05-27 09:51 UTC, ujjboy requested changes

2022-05-27 09:51 UTC, ujjboy commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_UNEXIST(1),
LOCK_NOT_EXISTS

2022-05-27 09:51 UTC, ujjboy commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            logger.error("try lock failed, {}", request, e);
这种写法有问题，不会打印堆栈

2022-05-27 09:51 UTC, ujjboy commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +           throw new NullPointerException("try lock request is null");
这个也换成 IllegalArgumentException 吧

2022-05-27 09:51 UTC, ujjboy commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            logger.debug("try lock request params {}", req);
可以提前判断一下 isDebugEnabled()

2022-05-27 09:51 UTC, ujjboy commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new NullPointerException("unlock request is null");
这个也换成 IllegalArgumentException 吧

2022-05-27 09:51 UTC, ujjboy commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            logger.error("unlock failed, {}", request, e);
这种写法有问题，不会打印堆栈

2022-07-16 14:04 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            logger.error("try lock failed, {}", request, e);
这个堆栈可以打印出来的

2022-07-16 14:04 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +           throw new NullPointerException("try lock request is null");
这里引用为空不应该用NullPointerException吗？

2022-07-16 14:04 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            logger.debug("try lock request params {}", req);
好的

2022-07-16 14:05 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new NullPointerException("unlock request is null");
同上

2022-07-16 14:05 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            logger.error("unlock failed, {}", request, e);
同上

2022-07-16 14:05 UTC, akkw commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_UNEXIST(1),
好的

2022-07-18 07:24 UTC, akkw commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            throw new RuntimeClientException(e);
这种感觉把异常抛给用户 异常是否打印日志让用户来决定就够了？如果用户也打印日志 这块日志就重复了

2022-07-29 13:40 UTC, seeflood requested changes

2022-07-29 13:40 UTC, seeflood commented on examples/src/test/java/io/mosn/layotto/examples/lock/EtcdLock.java
> +    static String storeName = "etcd";
I think the client example should be decoupled with specific implementation.
Better call it "lock_demo"

2022-07-29 13:40 UTC, seeflood commented on examples/src/test/java/io/mosn/layotto/examples/lock/RedisLock.java
> +    static String storeName = "etcd";
Same as above

2022-07-29 13:40 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +                    .getStatus();
Maybe we should check null ?

2022-07-29 13:40 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            return new UnlockResponse(status.getNumber());
Maybe we should check null ?

2022-08-20 07:58 UTC, seeflood requested changes

2022-08-20 07:58 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_NOT_EXISTS(1),
```suggestion
    LOCK_UNEXIST(1),
```

2022-08-20 07:58 UTC, seeflood commented on examples/src/test/java/io/mosn/layotto/examples/lock/RedisLock.java
> +public class RedisLock {
RedisLock  和  EtcdLock 是不是可以删掉一个、只保留一个，类名就叫 Lock，同一个 demo既能调 etcd、又能调 redis 或者其他组件

2022-08-20 10:15 UTC, akkw commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_NOT_EXISTS(1),
这个是什么问题？

2022-08-20 10:16 UTC, akkw commented on examples/src/test/java/io/mosn/layotto/examples/lock/RedisLock.java
> +public class RedisLock {
好的

2022-08-20 10:41 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_NOT_EXISTS(1),
最好和 proto 定义的枚举值一致~ 因为proto 上定义的是 `LOCK_UNEXIST`

2022-08-20 11:46 UTC, akkw commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_NOT_EXISTS(1),
> 最好和 proto 定义的枚举值一致~ 因为proto 上定义的是 `LOCK_UNEXIST`
从那个值改过来的😂

2022-08-21 13:51 UTC, seeflood approved these changes
lgtm

2022-08-21 13:53 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/lock/UnlockResponseStatus.java
> +    LOCK_UNEXIST(1),
尴尬 因为 proto 里的枚举值就叫 LOCK_UNEXIST 。。。

2022-08-22 07:05 UTC, zhenjunMa approved these changes

2022-08-25 08:22 UTC, merged

2022-08-25 08:25 UTC, seeflood commented
@akkw Thanks!
Could u help add this example into our quickstart doc?
Like we what we did for sequencer API, see https://mosn.io/layotto/#/zh/start/sequencer/start
![image](https://user-images.githubusercontent.com/26001097/186614574-c75b0fd2-35df-45b2-8632-0f713dbbc365.png)

2022-08-25 15:25 UTC, akkw commented
> @akkw Thanks! Could u help add this example into our quickstart doc? Like we what we did for sequencer API, see https://mosn.io/layotto/#/zh/start/sequencer/start ![image](https://user-images.githubusercontent.com/26001097/186614574-c75b0fd2-35df-45b2-8632-0f713dbbc365.png)

好的，可以