oss client & demo
layotto/java-sdk pull request #30
Opened 2022-08-26 12:29 UTC by zhenjunMa

2022-08-26 15:07 UTC, seeflood requested changes

2022-08-26 15:07 UTC, seeflood commented on spec/src/main/proto/oss.proto
> +service ObjectStorageService{
No need to add this file in this repo.

2022-08-29 03:54 UTC, wenxuwan submitted a review, later dismissed

2022-08-29 04:07 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/grpc/GrpcRuntimeClient.java
> +    StubManager<RuntimeGrpc.RuntimeStub, RuntimeGrpc.RuntimeBlockingStub> getRuntimeStubManager();
这个是不兼容改动，已有用户应该已经在用这个方法了，如果要改会很麻烦

2022-08-29 04:14 UTC, seeflood requested changes

2022-08-29 04:14 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/client/RuntimeClient.java
> +    StubManager<ObjectStorageServiceGrpc.ObjectStorageServiceStub, ObjectStorageServiceGrpc.ObjectStorageServiceBlockingStub> getOssManager();
这个接口设计的有点怪，要不：
- 单独弄个 OssRuntime interface，像其他的一样
- OssRuntime interface 提供 getOssBlockingStub 和 getOssAsyncStub 方法，而不是这个 getOssManager

2022-08-31 02:43 UTC, seeflood requested changes

2022-08-31 02:43 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientBuilder.java
> +            ossStubManager = new PooledStubManager<>(ip, port, poolSize, new OssStubCreatorImpl());
runtimeStubManager = new PooledStubManager<>(ip, port, poolSize, new RuntimeStubCreatorImpl());
这行会创建一个连接池（channels），下面 ossStubManager 又重新创建了一套连接池。
最好复用上面这行的 channels吧

2022-08-31 02:45 UTC, seeflood requested changes

2022-08-31 02:45 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +    public StubManager<RuntimeGrpc.RuntimeStub, RuntimeGrpc.RuntimeBlockingStub> getRuntimeStubManager() {
同上，这个接口生产用户应该已经在用了

2022-08-31 02:48 UTC, seeflood requested changes

2022-08-31 02:48 UTC, seeflood commented on README-zh.md
> -```
这段可以留着，在文档里标注下，“记得检查 proto 文件里有这些 option，例如 `spec/proto/runtime/v1/appcallback.proto` 文件中有这些blabla "

2022-08-31 02:48 UTC, seeflood commented on README.md
> -```
同上

2022-09-07 05:02 UTC, seeflood requested changes

2022-09-07 05:02 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/OssRuntime.java
> + * Created on 2022/9/1 4:41 下午
```suggestion
 * Created on 2022/9/1 16:41
```

2022-09-07 05:45 UTC, seeflood requested changes

2022-09-07 05:45 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +import spec.proto.runtime.v1.s3.ObjectStorageServiceGrpc;
The path is wrong

2022-09-07 05:54 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientBuilder.java
> +    public static class RuntimeStubCreatorImpl implements
这是个 public 的，要确认下改名字会不会影响生产用户

2022-09-07 05:55 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientBuilder.java
> +        StubManager<RuntimeGrpc.RuntimeStub, RuntimeGrpc.RuntimeBlockingStub> runtimeStubManager;
这是个 protected 的，要确认下改名字会不会影响生产用户

2022-09-08 07:28 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientBuilder.java
> +        StubManager<RuntimeGrpc.RuntimeStub, RuntimeGrpc.RuntimeBlockingStub> runtimeStubManager;
看错了 这个没问题

2022-09-08 07:28 UTC, seeflood approved these changes

2022-09-08 07:29 UTC, wenxuwan approved these changes
LGTM

2022-09-08 07:31 UTC, merged