[WIP]init shell data
layotto/java-sdk pull request #40
Opened 2022-09-17 15:08 UTC by LXPWing

2022-09-18 13:44 UTC, LXPWing commented
@seeflood redis的value插入什么文本

2022-09-27 12:54 UTC, seeflood commented
> @seeflood redis的value插入什么文本

抱歉刚看到！都行，得体即可, 例如 "This message comes from Alibaba Cloud ECS"

要不，消息从环境变量里读，或者从某个文件读？这样在阿里云和 aws 部署的时候，我可以配不同的消息

2022-09-27 13:00 UTC, seeflood commented
@LXPWing 脚本看起来没问题哈，就是要补充下输入redis 的kv，以及启动layotto的config.json，在 https://github.com/layotto/java-sdk/blob/main/examples-preview-service/config.json

2022-09-28 13:19 UTC, LXPWing commented
![image](https://user-images.githubusercontent.com/65880844/192788828-ccbe6dbf-6d61-489e-9a48-e6556a946b88.png)
启动layotto的config.json,好像原先就写好了

2022-09-28 13:34 UTC, LXPWing commented
redis的value，通过shell命令行传递文件路径参数例如 “sh start.sh test,txt”来读取

2022-09-29 03:05 UTC, seeflood commented
@LXPWing 
- 关于json
那个json 是我加的， 在 https://github.com/layotto/java-sdk/blob/main/examples-preview-service/config.json
但是json 里没有 redis、以及 file 组件的配置，你得改下json配置，以便集成redis和file

2022-09-29 03:07 UTC, seeflood commented
> redis的value，通过shell命令行传递文件路径参数例如 “sh start.sh test.txt”来读取

ok

2022-10-08 13:03 UTC, LXPWing commented
@seeflood 
![image](https://user-images.githubusercontent.com/65880844/194708897-52880d94-3a34-4a46-a6f4-11b91d90bdf9.png)
这里redis json不能使用环境变量，上服务的时候需要手动添加

2022-10-10 03:32 UTC, seeflood requested changes

2022-10-10 03:32 UTC, seeflood commented on examples-preview-service/config.json
> +                      "lock": {
state 也需要配置一下redis 组件哈

2022-10-10 03:40 UTC, seeflood requested changes

2022-10-10 03:40 UTC, seeflood commented on examples-preview-service/start.sh
> +#preview_path=$(pwd)
```suggestion
preview_path=$(pwd)
```
下面会用到这个变量，注释掉会有问题
![image](https://user-images.githubusercontent.com/26001097/194796269-c31fc362-7f75-48ce-8394-f72199107793.png)

2022-10-12 03:30 UTC, seeflood commented on examples-preview-service/start.sh
> +echo "======>Init redis date"
```suggestion
echo "======>Init redis data"
```

2022-10-12 03:31 UTC, seeflood approved these changes

2022-10-12 03:31 UTC, merged