feat: add secret for java sdk
layotto/java-sdk pull request #42
Opened 2022-09-25 11:56 UTC by fft0518

The PR is add secret api for java sdk and is one of the ospp projects.

In this PR, I have a problem that I don't how to convert SecretResponse type to Map type. So I also use the SecretResponse type althoug I think it's wrong.

https://github.com/mosn/layotto/issues/626

2022-09-26 07:43 UTC, seeflood requested changes

2022-09-26 07:43 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/SecretRuntime.java
> +public interface SecretRuntime {
`src/main/java/spec/sdk/runtime/v1/client/RuntimeClient.java` should also extend this interface
![image](https://user-images.githubusercontent.com/26001097/192220787-200052fb-3ee6-4498-b059-7e868372d769.png)

2022-09-26 08:19 UTC, fft0518 commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/SecretRuntime.java
> +public interface SecretRuntime {
Thanks.

2022-09-26 15:37 UTC, ZLBer commented
<img width="747" alt="image" src="https://user-images.githubusercontent.com/20033804/192319364-5887b4f6-9aac-483a-867a-21133ec1fc8c.png">

@fft0518  it has method to get `sercretsMap`

2022-09-27 04:45 UTC, ZLBer commented on examples-secret/src/main/java/io/mosn/layotto/examples/secret/Secret.java
> +
format code, remove blank line

2022-09-27 04:45 UTC, ZLBer commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +
same as above

2022-09-27 04:45 UTC, ZLBer commented
@fft0518  add a java example? like [examples-sequencer](https://github.com/layotto/java-sdk/tree/main/examples-sequencer)

2022-09-27 04:46 UTC, ZLBer commented
@fft0518  merge the master branch before push code
<img width="654" alt="image" src="https://user-images.githubusercontent.com/20033804/192434296-2ca26f81-27d1-49ee-aa3d-e4203c013702.png">

2022-09-27 05:50 UTC, fft0518 commented
> @fft0518 add a java example? like [examples-sequencer](https://github.com/layotto/java-sdk/tree/main/examples-sequencer)
I added it at the firsttime

2022-09-27 15:07 UTC, ZLBer submitted a review, later dismissed

2022-09-27 15:26 UTC, fft0518 commented
@seeflood please help to review it. Thanks.

2022-09-28 08:49 UTC, seeflood requested changes

2022-09-28 08:49 UTC, seeflood commented on examples-secret/pom.xml
> +        <version>1.2.0-SNAPSHOT</version>
Now it's `1.3.0-SNAPSHOT`. Please replace all the `1.2.0-SNAPSHOT` with `1.3.0-SNAPSHOT`

2022-09-28 08:58 UTC, seeflood requested changes

2022-09-28 08:58 UTC, seeflood commented on examples-secret/pom.xml
> +                            <mainClass>io.mosn.layotto.examples.sequencer.Secret</mainClass>
```suggestion
                            <mainClass>io.mosn.layotto.examples.secret.Secret</mainClass>
```

2022-09-28 09:06 UTC, seeflood requested changes

2022-09-28 09:06 UTC, seeflood commented on examples-secret/src/main/java/io/mosn/layotto/examples/secret/Secret.java
> +            System.out.println(client.getSecret(secretreq).getData());
Could u add some assertions here ?
For example, in `src/main/java/io/mosn/layotto/examples/lock/Lock.java`, we assert that the response is true/false:
![image](https://user-images.githubusercontent.com/26001097/192737865-afae42bf-bd80-4d0f-88ca-ae21a3d1e350.png)
The benefit of these assertions is that we can run these demos as test cases. 
For more details, check https://mosn.io/layotto/#/zh/development/test-quickstart?id=q-%e5%a6%82%e4%bd%95%e7%bc%96%e5%86%99%e5%85%b7%e6%9c%89quot%e5%8f%af%e6%b5%8b%e8%af%95%e6%80%a7quot%e7%9a%84%e6%96%87%e6%a1%a3

2022-09-28 09:07 UTC, seeflood requested changes

2022-09-28 09:07 UTC, seeflood commented on examples-secret/src/main/java/io/mosn/layotto/examples/secret/Secret.java
> +            System.out.println(client.getBulkSecret(bulksecretreq).getData());
same as above

2022-09-28 09:15 UTC, seeflood requested changes

2022-09-28 09:15 UTC, seeflood commented on sdk/src/main/java/spec/sdk/runtime/v1/domain/secret/GetBulkSecretRequest.java
> +        }
getter methods shouldn't modify the value.
I prefer to `return metaData` directly.

2022-09-28 09:36 UTC, seeflood requested changes

2022-09-28 09:36 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +                    .putAllMetadata(req.getMetaData())
Oh no, we have to check if the `req.getMetaData()` returns null here 😢

2022-09-28 09:36 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +                    .putAllMetadata(req.getMetaData())
Same as above

2022-09-28 09:39 UTC, seeflood requested changes

2022-09-28 09:39 UTC, seeflood commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
> +            for(Map.Entry<String,RuntimeProto.SecretResponse> entry : response.getDataMap().entrySet()){
Maybe we should check if `response.getDataMap()`  returns null here?

2022-09-28 10:57 UTC, seeflood requested changes

2022-09-28 10:57 UTC, seeflood commented on examples-secret/src/main/java/io/mosn/layotto/examples/secret/Secret.java
> +            Map<String, String> meta2 = new HashMap<>();
By the way, to run this demo in Layotto CI, you need to modify the [secret API quickstart documentation](https://mosn.io/layotto/#/zh/start/secret/start) .
![image](https://user-images.githubusercontent.com/26001097/192761976-00b0609e-a3c8-4897-9775-031368d6ff35.png)

You can take https://github.com/mosn/layotto/pull/783 as an example.
For more details, read https://mosn.io/layotto/#/zh/development/test-quickstart

2022-09-28 14:26 UTC, seeflood requested changes

2022-09-28 14:54 UTC, fft0518 commented
![image](https://user-images.githubusercontent.com/58096669/192812145-9ce9ba2b-1a2b-4906-9659-c97f7cadac63.png)
@seeflood  How can I resolve conflicts？

2022-09-29 02:58 UTC, seeflood approved these changes
lgtm. Thanks

2022-09-29 02:58 UTC, merged

2022-09-29 02:59 UTC, fft0518 commented
> lgtm. Thanks

Thanks!