feat: add configuration sdk
layotto/java-sdk pull request #50
Opened 2022-10-10 12:57 UTC by it-linnan

**What this PR does**:

Add configuration sdk

**Which issue(s) this PR fixes**:

Fixes https://github.com/mosn/layotto/issues/687

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-10-16 15:02 UTC, seeflood requested changes

2022-10-16 15:02 UTC, seeflood commented on examples-configuration/pom.xml
> +                            <mainClass>io.mosn.layotto.examples.configuration.Configuration</mainClass>
Where is this class ? I guess that you forgot to git commit it 🤔

2022-11-21 15:56 UTC, ZLBer approved these changes

2022-11-22 06:04 UTC, zhenjunMa approved these changes

2022-11-25 08:13 UTC, merged