add uds support for java sdk
layotto/java-sdk pull request #51
Opened 2023-09-08 06:14 UTC by ChloroplastYu

**What this PR does**:
add unix domain socket support for layotto-java-sdk
add a simple uds demo

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2023-09-11 09:58 UTC, wenxuwan submitted a review, later dismissed

2023-09-11 12:31 UTC, zhenjunMa requested changes

2023-09-11 12:31 UTC, zhenjunMa commented on sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientBuilder.java
> +                ossStubManager = new SingleStubManager<>(this.channel, new OssStubCreatorImpl());
这里也需要把上面的连接池模式适配一下

2023-09-11 12:35 UTC, zhenjunMa commented
另外要补充下单测，可以参考下别的例子，不过uds比较特殊，加个平台判断，只有linux的时候才执行

2023-09-11 12:35 UTC, zhenjunMa commented
另外要补充下单测，可以参考下别的例子，不过uds比较特殊，加个平台判断，只有linux的时候才执行

2023-09-12 06:31 UTC, ChloroplastYu commented
@zhenjunMa @zhenjunMa 连接池模式适配好了，单测也补上了。另外顺手做了点小重构，麻烦两位大佬再review下

2023-09-14 08:24 UTC, wenxuwan approved these changes

2023-09-14 09:15 UTC, merged