feat: layotto springboot
layotto/java-sdk pull request #8
Opened 2021-12-24 07:04 UTC by ZLBer

related issue: https://github.com/mosn/layotto/issues/371
- add layotto springboot
- move  RawSubscriber and EvenListener  from examples to sdk, renamed DefaultSubscriber
- add springboot examples

2021-12-24 15:06 UTC, seeflood commented
Coool !
@zhenjunMa @MoonShining @RayneHwang Could u help review this PR?

2022-01-04 08:17 UTC, ujjboy requested changes

2022-01-04 08:17 UTC, ujjboy commented on pom.xml
> +           <!-- <plugin>
这个格式化的插件可以直接删掉，在父pom里有

2022-01-04 08:17 UTC, ujjboy commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoBeanPostProcessor.java
> +    static Map<String, DefaultSubscriber> SubscriberMap = new HashMap<>();
字段名小写开头

2022-01-04 08:17 UTC, ujjboy commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoBeanPostProcessor.java
> +    static Map<String, DefaultSubscriber> SubscriberMap = new HashMap<>();
考虑并发  换成 ConcurrentHashMap 吧

2022-01-04 08:17 UTC, ujjboy commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoSubscriberStarter.java
> +            e.printStackTrace();
e.printStackTrace();  用  logger

2022-01-04 08:17 UTC, ujjboy commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoEventListener.java
> +            e.printStackTrace();
e.printStackTrace(); 不要

2022-01-04 08:17 UTC, ujjboy commented on sdk/src/main/java/io/mosn/layotto/v1/Topic.java
> +import java.lang.annotation.*;
不要 import  *

2022-01-05 05:32 UTC, ZLBer commented
@ujjboy  thanks for your review, all resolved.

2022-02-10 08:11 UTC, ujjboy requested changes

2022-02-10 08:11 UTC, ujjboy commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoSubscriberStarter.java
> +    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
没看到使用 applicationContext，这里为啥要实现 ApplicationContextAware？
直接用普通 Bean 的 PostConstruct 之类的不行吗？

2022-02-25 06:35 UTC, ZLBer commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoSubscriberStarter.java
> +    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
确实可以，之前忘记加component注解导致PostConstruct失效。

2022-03-02 03:53 UTC, ZLBer commented
@ujjboy   all resolved

2022-03-08 08:24 UTC, ujjboy requested changes

2022-03-08 08:24 UTC, ujjboy commented on sdk-springboot/src/main/java/io/mosn/layotto/springboot/LayottoAutoConfiguration.java
> +@ComponentScan("io.mosn.layotto.springboot")
不建议在 AutoConfiguration 使用 ComponentScan，一般 AutoConfiguration  的写法是：
1.  声明 Conditional  例如存在某些 class， 存在某些配置开始，依赖哪些其它的AutoConfiguration
2. 通过 `@Bean` 的方式去声明这个 Starter 里要自动化的加载哪些类。


所以应该把 LayottoBeanPostProcessor 和 LayottoConfig 里的  `Component`  去掉，放到这里初始化。

可以参考官方的例子：https://docs.spring.io/spring-boot/docs/2.3.12.RELEASE/reference/html/appendix-auto-configuration-classes.html#auto-configuration-classes

2022-03-11 06:30 UTC, ZLBer commented
@ujjboy 去掉了`Component`和`ComponentScan`, 改成了`ConditionalOnMissingBean`和`ConfigurationProperties`

2022-03-17 02:33 UTC, ujjboy approved these changes
LGTM

2022-03-18 08:01 UTC, seeflood approved these changes
lgtm. Thanks 斌哥!

2022-03-18 08:03 UTC, zhenjunMa approved these changes

2022-03-18 08:08 UTC, merged